package com.lucasserafin94.iptvburo.desktop.license

import com.lucasserafin94.iptvburo.domain.model.EntitlementState
import java.nio.charset.StandardCharsets
import java.security.KeyFactory
import java.security.Signature
import java.security.spec.X509EncodedKeySpec
import java.util.Base64
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.time.Instant

/**
 * The client accepts what the server actually produces.
 *
 * Every other test in this package signs with Kotlin and verifies with Kotlin, which proves the two
 * halves of one implementation agree with each other. It would pass just as happily if both were
 * wrong in the same way — and the server is not Kotlin. It is JavaScript running in a Cloudflare
 * Worker, using Web Crypto.
 *
 * The fixture below was produced by running the Worker's own `signLicense` under Node. If the two
 * implementations ever disagree — a different key encoding, a different byte order, a canonical
 * form applied on one side only — this fails, and it fails here rather than on a customer's machine
 * where the symptom would be "the app says my licence is invalid".
 *
 * The key pair is a throwaway generated for this test. The real signing key lives only in the
 * Worker's secrets and is never in this repository.
 */
class ServerInteropTest {
    /** Generated by `generate-keys.mjs`, used for nothing else. */
    private val serverPublicKey =
        "MCowBQYDK2VwAyEAu64j3zdO6wIBHOUeVjNcOVT5fv1kx9n2JVnZB1py1Is="

    /** Produced by the Worker's `signLicense`, verbatim. */
    private val payload =
        """{"deviceId":"FP86-XARB-9JZW","nonce":"test-challenge-1234","serverTime":"2026-08-08T12:00:00Z","state":"TRIAL","trialEndsAt":"2026-08-15T12:00:00Z"}"""

    private val signature =
        "OGBQuo6x/F56q46HreeIG2zh8MKRFuMMqaC4lnFKUUp/IGjKaphohemgvWP/KixLwDzE/kjxS5XXhvMyygEaCw=="

    private val deviceId = "FP86-XARB-9JZW"

    /** The whole point: a document signed by the real server verifies in the real client. */
    @Test
    fun `a licence signed by the worker verifies in the client`() {
        val licence = SignedLicense(payload = payload, signatureBase64 = signature)

        val verified =
            assertNotNull(
                licence.verified(serverPublicKey, deviceId, expectedNonce = "test-challenge-1234"),
                "the client rejected a genuine server signature — the two implementations disagree",
            )

        assertEquals(EntitlementState.TRIAL, verified.state)
        assertEquals(Instant.parse("2026-08-15T12:00:00Z"), verified.trialEndsAt)
        assertEquals(Instant.parse("2026-08-08T12:00:00Z"), verified.serverTimeAt)
    }

    /** And the same document with one byte changed does not, so the check is real. */
    @Test
    fun `a tampered server licence is rejected`() {
        val tampered = payload.replace("2026-08-15", "2099-08-15")

        assertNull(
            SignedLicense(tampered, signature).verified(serverPublicKey, deviceId, "test-challenge-1234"),
        )
    }

    /**
     * The stored-licence path, where no challenge is demanded.
     *
     * A document that carries a nonce still verifies when none is expected: that is how a licence
     * fetched online is later read back offline.
     */
    @Test
    fun `the same licence verifies offline without a challenge`() {
        val licence = SignedLicense(payload, signature)

        assertNotNull(licence.verified(serverPublicKey, deviceId, expectedNonce = null))
    }

    /**
     * WebCrypto and the JDK use the same SPKI bytes, BURO base32 derivation and P1363 signature.
     *
     * This fixture was generated with `crypto.subtle` under Node. It catches the easy interoperability
     * mistake where Java emits ASN.1 DER ECDSA signatures while WebCrypto expects fixed-width r||s.
     */
    @Test
    fun `a WebCrypto P-256 installation proof verifies in the Windows client`() {
        val installationId = "33333333-3333-4333-8333-333333333333"
        val publicKeyBase64 =
            "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoqQy0VcXg9Mhj/rFI6+sy7w48ty+hrgvfRJevPw/WBpRDnXVNQkX+7OYwcf9TodZbDTgcreGEIzoSN8QwvtfiQ=="
        val expectedDeviceId = "F7WM-HWE3-SDHV"
        val nonce = "InteropProofNonce1234A"
        val proof =
            "T1xv7-AhAU-M3nq-Sg-3jOMm_xlLurYTQJNGxJzwtk1G0FLNfVTNEKZd9rnlSgC7eugdj6sJrGRX_HtujyuXyg"
        val publicBytes = Base64.getDecoder().decode(publicKeyBase64)

        assertEquals(expectedDeviceId, deriveDeviceId(installationId, publicBytes))

        val publicKey =
            KeyFactory.getInstance("EC").generatePublic(X509EncodedKeySpec(publicBytes))
        val verifier = Signature.getInstance("SHA256withECDSAinP1363Format")
        verifier.initVerify(publicKey)
        verifier.update(
            canonicalDeviceProof(DeviceProofAction.REGISTER, expectedDeviceId, nonce)
                .toByteArray(StandardCharsets.UTF_8),
        )
        kotlin.test.assertTrue(verifier.verify(Base64.getUrlDecoder().decode(proof)))
    }
}
