package com.lucasserafin94.iptvburo.desktop.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.staticCompositionLocalOf
import com.lucasserafin94.iptvburo.desktop.user.DesktopLanguage

/**
 * Every user-visible string on Windows.
 *
 * Modelled as a data class rather than a `Map<String, String>` on purpose: a missing translation is
 * a compile error instead of a runtime `NoSuchElementException`, and the tables are allocated once
 * at class-init instead of on every recomposition.
 */
data class DesktopStrings(
    // Shell
    val library: String,
    val home: String,
    val live: String,
    val movies: String,
    val series: String,
    val favorites: String,
    val search: String,
    val sources: String,
    val profile: String,
    val yourLibrary: String,
    val connectXtream: String,
    val importM3u: String,
    val checkUpdate: String,
    val refreshCatalog: String,
    val checkingUpdate: String,
    val upToDate: String,
    val downloading: String,
    val installerVerified: String,
    val updateFailed: String,
    val privateSession: String,
    val nothingSensitiveSaved: String,
    // Home
    val dailySelection: String,
    val continueWatching: String,
    val moviesForToday: String,
    val seriesToExplore: String,
    val liveNow: String,
    val heroFallbackTitle: String,
    val heroSubtitle: String,
    val watchNow: String,
    val details: String,
    val options: String,
    val organizingToday: String,
    val tryAgain: String,
    val watched: String,
    val onAir: String,
    // States
    val emptyHeadline: String,
    val emptyBody: String,
    val emptyBadge: String,
    val credentialsStayLocal: String,
    val authenticating: String,
    val organizingPlaylist: String,
    val noSensitiveData: String,
    val close: String,
    val cancel: String,
    val understood: String,
    val whoIsWatching: String,
    val newProfile: String,
    val addProfile: String,
    val kidsProfile: String,
    val adultProfile: String,
    val forgetSource: String,
    val searchChannel: String,
    val results: String,
    val items: String,
    val sourcesCount: String,
    val selectChannel: String,
    val vaultProtected: String,
    val credentialsEncrypted: String,
    // Catalogue workspace
    val endSession: String,
    val searchCatalog: String,
    val categories: String,
    val allCategories: String,
    val catalog: String,
    val noMatch: String,
    val previous: String,
    val next: String,
    val page: String,
    val allYears: String,
    val releasesIn: String,
    val sessionActive: String,
    val loadingCatalog: String,
    val sessionClosed: String,
    val backToCatalog: String,
    val selectItem: String,
    val download: String,
    val downloadInProgress: String,
    val downloaded: String,
    val downloadFailed: String,
    val removeDownload: String,
    val downloads: String,
    val resetSettings: String,
    val resetConfirm: String,
    val resetWarning: String,
    val settings: String,
    val languageLabel: String,
    val chooseYear: String,
    val downloadPaused: String,
    val downloadsEmptyTitle: String,
    val downloadsEmptyBody: String,
    val updateReadyBody: String,
    val updateRestartNow: String,
    val updateLater: String,
) {
    companion object {
        fun of(language: DesktopLanguage): DesktopStrings =
            when (language) {
                DesktopLanguage.PORTUGUESE_BRAZIL -> PtBr
                DesktopLanguage.ENGLISH -> En
                DesktopLanguage.GERMAN -> De
                DesktopLanguage.ITALIAN -> It
            }

        private val PtBr =
            DesktopStrings(
                library = "BIBLIOTECA",
                home = "Início",
                live = "Ao vivo",
                movies = "Filmes",
                series = "Séries",
                favorites = "Favoritos",
                search = "Pesquisa",
                sources = "FONTES",
                profile = "Perfil",
                yourLibrary = "Sua biblioteca",
                connectXtream = "Conectar Xtream",
                importM3u = "Importar M3U",
                checkUpdate = "Verificar atualização",
                refreshCatalog = "Atualizar listas",
                checkingUpdate = "Verificando atualização…",
                upToDate = "Você já está na versão mais recente.",
                downloading = "Baixando",
                installerVerified = "Instalador verificado. Atualizando…",
                updateFailed = "A atualização não pôde ser instalada.",
                privateSession = "Sessão privada",
                nothingSensitiveSaved = "Nada sensível é salvo",
                dailySelection = "SELEÇÃO DIÁRIA",
                continueWatching = "Continuar assistindo",
                moviesForToday = "Filmes escolhidos para hoje",
                seriesToExplore = "Séries para continuar explorando",
                liveNow = "Ao vivo agora",
                heroFallbackTitle = "Sua biblioteca está pronta",
                heroSubtitle =
                    "Uma seleção diferente a cada dia, organizada sem misturar toda a biblioteca " +
                        "na mesma tela.",
                watchNow = "Assistir",
                details = "Ver detalhes",
                options = "opções",
                organizingToday = "Organizando a seleção de hoje…",
                tryAgain = "Tentar novamente",
                watched = "assistido",
                onAir = "AO VIVO",
                emptyHeadline = "Toda a sua biblioteca.\nSem ruído.",
                emptyBody =
                    "Importe sua fonte autorizada e deixe o IPTV BURO organizar canais, filmes e " +
                        "séries numa experiência única em todas as telas.",
                emptyBadge = "BURO NOCTURNE  •  BIBLIOTECA PRIVADA",
                credentialsStayLocal = "A fonte é reconectada com o cofre protegido deste usuário.",
                authenticating = "Autenticando e preparando o catálogo…",
                organizingPlaylist = "Organizando sua playlist…",
                noSensitiveData = "Nenhum dado sensível será salvo.",
                close = "Fechar",
                cancel = "Cancelar",
                understood = "Entendi",
                whoIsWatching = "Quem está assistindo?",
                newProfile = "Novo perfil",
                addProfile = "Adicionar",
                kidsProfile = "Perfil infantil",
                adultProfile = "Perfil adulto",
                forgetSource = "Esquecer fonte",
                searchChannel = "Buscar canal…",
                results = "resultados",
                items = "itens",
                sourcesCount = "fontes",
                selectChannel = "Selecione um canal",
                vaultProtected = "Cofre protegido",
                credentialsEncrypted = "Credenciais cifradas pelo Windows",
                endSession = "Encerrar sessão",
                searchCatalog = "Buscar neste catálogo…",
                categories = "Categorias",
                allCategories = "Todas",
                catalog = "Catálogo",
                noMatch = "Nenhum item corresponde ao filtro.",
                previous = "Anterior",
                next = "Próxima",
                page = "Página",
                allYears = "Todos os anos",
                releasesIn = "Lançamentos",
                sessionActive = "Sessão ativa · conexão protegida no Windows",
                loadingCatalog = "Carregando catálogo…",
                sessionClosed = "Sessão encerrada",
                backToCatalog = "Voltar ao catálogo",
                selectItem = "Selecione um item",
                download = "Baixar",
                downloadInProgress = "Baixando",
                downloaded = "Baixado",
                downloadFailed = "Falha no download",
                removeDownload = "Remover download",
                downloads = "Downloads",
                resetSettings = "Redefinir configuracoes",
                resetConfirm = "Apagar tudo",
                resetWarning = "Isso apaga perfis, favoritos e progresso. Os arquivos baixados sao mantidos.",
                settings = "Configuracoes",
                languageLabel = "IDIOMA",
                chooseYear = "Escolher ano",
                downloadPaused = "Pausado",
                downloadsEmptyTitle = "Nenhuma copia offline",
                downloadsEmptyBody = "Abra um filme e escolha Baixar. As copias salvas aparecem aqui e tocam sem internet.",
                updateReadyBody = "A atualizacao foi baixada e verificada. O aplicativo precisa fechar para concluir a instalacao.",
                updateRestartNow = "Fechar e atualizar",
                updateLater = "Depois",
            )

        private val En =
            DesktopStrings(
                library = "LIBRARY",
                home = "Home",
                live = "Live TV",
                movies = "Movies",
                series = "Series",
                favorites = "Favorites",
                search = "Search",
                sources = "SOURCES",
                profile = "Profile",
                yourLibrary = "Your library",
                connectXtream = "Connect Xtream",
                importM3u = "Import M3U",
                checkUpdate = "Check for update",
                refreshCatalog = "Refresh lists",
                checkingUpdate = "Checking for update…",
                upToDate = "You are already on the latest version.",
                downloading = "Downloading",
                installerVerified = "Installer verified. Updating…",
                updateFailed = "The update could not be installed.",
                privateSession = "Private session",
                nothingSensitiveSaved = "Nothing sensitive is stored",
                dailySelection = "DAILY SELECTION",
                continueWatching = "Continue watching",
                moviesForToday = "Movies picked for today",
                seriesToExplore = "Series worth exploring",
                liveNow = "Live now",
                heroFallbackTitle = "Your library is ready",
                heroSubtitle =
                    "A different selection every day, arranged without dumping the whole library " +
                        "onto one screen.",
                watchNow = "Watch",
                details = "Details",
                options = "options",
                organizingToday = "Arranging today's selection…",
                tryAgain = "Try again",
                watched = "watched",
                onAir = "LIVE",
                emptyHeadline = "Your whole library.\nNo noise.",
                emptyBody =
                    "Import your authorised source and let IPTV BURO arrange channels, movies and " +
                        "series into one experience across every screen.",
                emptyBadge = "BURO NOCTURNE  •  PRIVATE LIBRARY",
                credentialsStayLocal = "The source reconnects from this user's protected vault.",
                authenticating = "Authenticating and preparing the catalogue…",
                organizingPlaylist = "Organising your playlist…",
                noSensitiveData = "No sensitive data will be stored.",
                close = "Close",
                cancel = "Cancel",
                understood = "Got it",
                whoIsWatching = "Who's watching?",
                newProfile = "New profile",
                addProfile = "Add",
                kidsProfile = "Kids profile",
                adultProfile = "Adult profile",
                forgetSource = "Forget source",
                searchChannel = "Search channel…",
                results = "results",
                items = "items",
                sourcesCount = "sources",
                selectChannel = "Select a channel",
                vaultProtected = "Vault protected",
                credentialsEncrypted = "Credentials encrypted by Windows",
                endSession = "End session",
                searchCatalog = "Search this catalogue…",
                categories = "Categories",
                allCategories = "All",
                catalog = "Catalogue",
                noMatch = "Nothing matches this filter.",
                previous = "Previous",
                next = "Next",
                page = "Page",
                allYears = "All years",
                releasesIn = "Released in",
                sessionActive = "Session active · connection protected on Windows",
                loadingCatalog = "Loading catalogue…",
                sessionClosed = "Session ended",
                backToCatalog = "Back to catalogue",
                selectItem = "Select an item",
                download = "Download",
                downloadInProgress = "Downloading",
                downloaded = "Downloaded",
                downloadFailed = "Download failed",
                removeDownload = "Remove download",
                downloads = "Downloads",
                resetSettings = "Reset settings",
                resetConfirm = "Erase everything",
                resetWarning = "This erases profiles, favourites and progress. Downloaded files are kept.",
                settings = "Settings",
                languageLabel = "LANGUAGE",
                chooseYear = "Choose year",
                downloadPaused = "Paused",
                downloadsEmptyTitle = "No offline copies",
                downloadsEmptyBody = "Open a film and choose Download. Stored copies appear here and play without a connection.",
                updateReadyBody = "The update was downloaded and verified. The app must close to finish installing.",
                updateRestartNow = "Close and update",
                updateLater = "Later",
            )

        private val De =
            DesktopStrings(
                library = "BIBLIOTHEK",
                home = "Start",
                live = "Live-TV",
                movies = "Filme",
                series = "Serien",
                favorites = "Favoriten",
                search = "Suche",
                sources = "QUELLEN",
                profile = "Profil",
                yourLibrary = "Deine Bibliothek",
                connectXtream = "Xtream verbinden",
                importM3u = "M3U importieren",
                checkUpdate = "Nach Update suchen",
                refreshCatalog = "Listen aktualisieren",
                checkingUpdate = "Suche nach Update…",
                upToDate = "Du hast bereits die neueste Version.",
                downloading = "Lädt herunter",
                installerVerified = "Installer geprüft. Wird aktualisiert…",
                updateFailed = "Das Update konnte nicht installiert werden.",
                privateSession = "Private Sitzung",
                nothingSensitiveSaved = "Nichts Sensibles wird gespeichert",
                dailySelection = "TAGESAUSWAHL",
                continueWatching = "Weiterschauen",
                moviesForToday = "Filme für heute",
                seriesToExplore = "Serien zum Entdecken",
                liveNow = "Jetzt live",
                heroFallbackTitle = "Deine Bibliothek ist bereit",
                heroSubtitle =
                    "Jeden Tag eine andere Auswahl – geordnet, ohne die ganze Bibliothek auf " +
                        "einen Bildschirm zu kippen.",
                watchNow = "Ansehen",
                details = "Details",
                options = "Optionen",
                organizingToday = "Die Auswahl von heute wird zusammengestellt…",
                tryAgain = "Erneut versuchen",
                watched = "gesehen",
                onAir = "LIVE",
                emptyHeadline = "Deine ganze Bibliothek.\nOhne Lärm.",
                emptyBody =
                    "Importiere deine autorisierte Quelle und lass IPTV BURO Kanäle, Filme und " +
                        "Serien zu einem Erlebnis auf allen Bildschirmen ordnen.",
                emptyBadge = "BURO NOCTURNE  •  PRIVATE BIBLIOTHEK",
                credentialsStayLocal =
                    "Die Quelle wird aus dem geschützten Tresor dieses Benutzers wiederhergestellt.",
                authenticating = "Authentifizierung und Katalogaufbau…",
                organizingPlaylist = "Deine Playlist wird geordnet…",
                noSensitiveData = "Es werden keine sensiblen Daten gespeichert.",
                close = "Schließen",
                cancel = "Abbrechen",
                understood = "Verstanden",
                whoIsWatching = "Wer schaut?",
                newProfile = "Neues Profil",
                addProfile = "Hinzufügen",
                kidsProfile = "Kinderprofil",
                adultProfile = "Erwachsenenprofil",
                forgetSource = "Quelle vergessen",
                searchChannel = "Kanal suchen…",
                results = "Ergebnisse",
                items = "Einträge",
                sourcesCount = "Quellen",
                selectChannel = "Wähle einen Kanal",
                vaultProtected = "Tresor geschützt",
                credentialsEncrypted = "Zugangsdaten von Windows verschlüsselt",
                endSession = "Sitzung beenden",
                searchCatalog = "In diesem Katalog suchen…",
                categories = "Kategorien",
                allCategories = "Alle",
                catalog = "Katalog",
                noMatch = "Nichts entspricht diesem Filter.",
                previous = "Zurück",
                next = "Weiter",
                page = "Seite",
                allYears = "Alle Jahre",
                releasesIn = "Erschienen",
                sessionActive = "Sitzung aktiv · Verbindung unter Windows geschützt",
                loadingCatalog = "Katalog wird geladen…",
                sessionClosed = "Sitzung beendet",
                backToCatalog = "Zurück zum Katalog",
                selectItem = "Wähle einen Eintrag",
                download = "Herunterladen",
                downloadInProgress = "Wird geladen",
                downloaded = "Geladen",
                downloadFailed = "Download fehlgeschlagen",
                removeDownload = "Download entfernen",
                downloads = "Downloads",
                resetSettings = "Einstellungen zuruecksetzen",
                resetConfirm = "Alles loeschen",
                resetWarning = "Loescht Profile, Favoriten und Fortschritt. Heruntergeladene Dateien bleiben.",
                settings = "Einstellungen",
                languageLabel = "SPRACHE",
                chooseYear = "Jahr wählen",
                downloadPaused = "Pausiert",
                downloadsEmptyTitle = "Keine Offline-Kopien",
                downloadsEmptyBody = "Oeffne einen Film und waehle Herunterladen. Gespeicherte Kopien erscheinen hier und laufen ohne Verbindung.",
                updateReadyBody = "Das Update wurde geladen und geprueft. Die App muss sich schliessen, um die Installation abzuschliessen.",
                updateRestartNow = "Schliessen und aktualisieren",
                updateLater = "Spaeter",
            )

        private val It =
            DesktopStrings(
                library = "LIBRERIA",
                home = "Home",
                live = "TV in diretta",
                movies = "Film",
                series = "Serie",
                favorites = "Preferiti",
                search = "Cerca",
                sources = "FONTI",
                profile = "Profilo",
                yourLibrary = "La tua libreria",
                connectXtream = "Connetti Xtream",
                importM3u = "Importa M3U",
                checkUpdate = "Cerca aggiornamenti",
                refreshCatalog = "Aggiorna elenchi",
                checkingUpdate = "Ricerca aggiornamenti…",
                upToDate = "Hai già la versione più recente.",
                downloading = "Download in corso",
                installerVerified = "Installer verificato. Aggiornamento…",
                updateFailed = "Non è stato possibile installare l'aggiornamento.",
                privateSession = "Sessione privata",
                nothingSensitiveSaved = "Nulla di sensibile viene salvato",
                dailySelection = "SELEZIONE DEL GIORNO",
                continueWatching = "Continua a guardare",
                moviesForToday = "Film scelti per oggi",
                seriesToExplore = "Serie da esplorare",
                liveNow = "In diretta ora",
                heroFallbackTitle = "La tua libreria è pronta",
                heroSubtitle =
                    "Una selezione diversa ogni giorno, organizzata senza riversare l'intera " +
                        "libreria in un'unica schermata.",
                watchNow = "Guarda",
                details = "Dettagli",
                options = "opzioni",
                organizingToday = "Sto preparando la selezione di oggi…",
                tryAgain = "Riprova",
                watched = "guardato",
                onAir = "IN DIRETTA",
                emptyHeadline = "Tutta la tua libreria.\nSenza rumore.",
                emptyBody =
                    "Importa la tua fonte autorizzata e lascia che IPTV BURO organizzi canali, " +
                        "film e serie in un'unica esperienza su ogni schermo.",
                emptyBadge = "BURO NOCTURNE  •  LIBRERIA PRIVATA",
                credentialsStayLocal =
                    "La fonte viene riconnessa dalla cassaforte protetta di questo utente.",
                authenticating = "Autenticazione e preparazione del catalogo…",
                organizingPlaylist = "Sto organizzando la tua playlist…",
                noSensitiveData = "Nessun dato sensibile verrà salvato.",
                close = "Chiudi",
                cancel = "Annulla",
                understood = "Ho capito",
                whoIsWatching = "Chi sta guardando?",
                newProfile = "Nuovo profilo",
                addProfile = "Aggiungi",
                kidsProfile = "Profilo bambini",
                adultProfile = "Profilo adulti",
                forgetSource = "Dimentica fonte",
                searchChannel = "Cerca canale…",
                results = "risultati",
                items = "elementi",
                sourcesCount = "fonti",
                selectChannel = "Seleziona un canale",
                vaultProtected = "Cassaforte protetta",
                credentialsEncrypted = "Credenziali cifrate da Windows",
                endSession = "Termina sessione",
                searchCatalog = "Cerca in questo catalogo…",
                categories = "Categorie",
                allCategories = "Tutte",
                catalog = "Catalogo",
                noMatch = "Nessun elemento corrisponde al filtro.",
                previous = "Precedente",
                next = "Successiva",
                page = "Pagina",
                allYears = "Tutti gli anni",
                releasesIn = "Usciti nel",
                sessionActive = "Sessione attiva · connessione protetta su Windows",
                loadingCatalog = "Caricamento del catalogo…",
                sessionClosed = "Sessione terminata",
                backToCatalog = "Torna al catalogo",
                selectItem = "Seleziona un elemento",
                download = "Scarica",
                downloadInProgress = "Scaricamento",
                downloaded = "Scaricato",
                downloadFailed = "Download non riuscito",
                removeDownload = "Rimuovi download",
                downloads = "Download",
                resetSettings = "Reimposta impostazioni",
                resetConfirm = "Cancella tutto",
                resetWarning = "Cancella profili, preferiti e avanzamento. I file scaricati restano.",
                settings = "Impostazioni",
                languageLabel = "LINGUA",
                chooseYear = "Scegli anno",
                downloadPaused = "In pausa",
                downloadsEmptyTitle = "Nessuna copia offline",
                downloadsEmptyBody = "Apri un film e scegli Scarica. Le copie salvate compaiono qui e si riproducono senza connessione.",
                updateReadyBody = "L aggiornamento e stato scaricato e verificato. L app deve chiudersi per completare l installazione.",
                updateRestartNow = "Chiudi e aggiorna",
                updateLater = "Piu tardi",
            )
    }
}

/**
 * Ambient string table.
 *
 * Screens read this instead of threading a `DesktopLanguage` parameter through every composable,
 * which is what left most of the UI hardcoded in Portuguese.
 */
val LocalDesktopStrings: ProvidableCompositionLocal<DesktopStrings> =
    staticCompositionLocalOf { DesktopStrings.of(DesktopLanguage.PORTUGUESE_BRAZIL) }

/** Shorthand for `LocalDesktopStrings.current`. */
val strings: DesktopStrings
    @Composable get() = LocalDesktopStrings.current
